---
services:
  sm2:
    image: node:24-alpine
    container_name: sm2
    working_dir: /home/node/app
    volumes:
      - ../scripts:/home/node/scripts:ro
      - ../app:/home/node/app
    ports:
      - 40000:3000
    command: "/home/node/scripts/setup.sh"
    restart: unless-stopped